application/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

application/main/routes.py
from os import name
from flask import Blueprint, request, redirect
from flask.templating import render_template
from application.models import Post
from application.main.utils import location_codes, names_tags
from application.main.forms import LocationForm

main = Blueprint('main', __name__)

@main.route('/', methods=['GET'])
@main.route('/homepage', methods=['GET'])
def home():
    page = request.args.get('page', type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/weather',methods=['GET', 'POST'])
def weather():
    codes = location_codes
    form = LocationForm()
    form.location.choices = list(codes.keys())
    if form.validate_on_submit():
        location = form.location.data
        return redirect("https://www.accuweather.com/en/in/" + location + "/" + codes[location] +\
     "/current-weather/" + codes[location])
    return render_template('weather.html',title='Weather', form=form, legend='Weather')

@main.route('/troezians', methods=['GET','POST'])
def view_pics():
    tags = names_tags
    return render_template('troezians.html', tags=tags)

application/posts/routes.py
from flask.helpers import url_for
from application.posts.forms import PostForm
from flask import Blueprint,flash, redirect, request, abort
from flask.templating import render_template
from application.models import Post
from application import db
from flask_login import current_user, login_required


posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post=Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your form has been submitted', 'success')
        return redirect(url_for('users.user_posts', username=current_user.username))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form=PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    
    return render_template('create_post.html', title='New Post', form=form, legend = 'Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'success')
    return redirect(url_for('main.home'))

application/transactions/routes.py
from application.transactions.forms import TransactionForm
from flask import Blueprint,flash, redirect, request, abort, render_template, url_for
from application.models import Transaction
from application import db
from flask_login import current_user, login_required

transactions = Blueprint('transactions', __name__)

@transactions.route('/transaction/new', methods=['GET', 'POST'])
@login_required
def new_transaction():
    form = TransactionForm()
    if form.validate_on_submit():
        transaction = Transaction(content = form.content.data, amount_paid = form.amount_paid.data,
        amount_received = form.amount_received.data, creator=current_user)
        db.session.add(transaction)
        db.session.commit()
        flash('Your transaction has been added', 'success')
        return redirect(url_for('users.user_transactions', username=current_user.username))
    return render_template('new_transaction.html', title="New Transaction", form=form, legend="New Transaction")

@transactions.route('/transaction/<int:transaction_id>')
@login_required
def transaction(transaction_id):
    transaction = Transaction.query.get_or_404(transaction_id)
    return render_template('transaction.html', content=transaction.content, transaction=transaction)

application/users/routes.py
from flask.helpers import url_for
from application.users.forms import LoginForm, RegistrationForm, UpdateAccountForm
from flask import Blueprint,flash, redirect, request
from flask.templating import render_template
from application.models import Transaction, User, Post
from application import db, bcrypt
from application.users.utils import upload_to_s3
from flask_login import login_user, logout_user, current_user, login_required
import os


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect('/homepage')
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You can now login.', 'success')
        return redirect('/login')
    return render_template('register.html', title = 'Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect('/homepage')
    form = LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect('/homepage')
        else:
            flash('Failed to log in. Please check email and password', 'danger')
    return render_template('login.html', title = 'Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect('/homepage')

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = upload_to_s3(form.picture.data, os.environ.get('AWS_STORAGE_BUCKET_NAME'))
            current_user.image_file = picture_file
            # current_user.image_file = form.picture.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route('/user/<string:username>/transactions')
def user_transactions(username):
    page = request.args.get('page', type=int)
    user = User.query.filter_by(username=username).first_or_404()
    transactions = Transaction.query.filter_by(creator=user)\
        .order_by(Transaction.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_transactions.html', transactions=transactions, user=user)

application/templates/about.html
{% extends 'base.html' %}
{% block head %}
<title>About</title>
{% endblock %}
{% block body %}
<div>
    <h1>About Farmer's website</h1>
    <p>Raithu Nestham is for the new age farmer. It is aimed at providing the necessary tools that help
        farmer in saving valuable manpower and bring automation into their lives.
    </p>
</div>
{% endblock %}

application/templates/account.html
{% extends 'base.html' %}
{% block head %}
<title>{{ current_user.username }}'s Account</title>
{% endblock %}
{% block body %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img"
            src="{{ url_for('static', filename='profile_pics/'+current_user.image_file) }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username}}</h2>
            <p class="text-secondary">{{ current_user.email}}</p>
        </div>
    </div>
    <form method="POST" action="" , enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class='text-danger'>{{ error }}</span></br>
                {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}

application/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    {% block head %}
    {% endblock %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-light bg-steel fixed-top" style="background-color: #36b866;">
            <div class="container">
                <a class="navbar-brand mr-4" href="/"><b>Raithu Nestham</b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="/">Home</a>
                        <a class="nav-item nav-link" href="/about">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('transactions.new_transaction') }}">New
                            Transaction</a>
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages=get_flashed_messages(with_categories=True) %}
                {% if messages%}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                {% block body %}{% endblock %}
            </div>
            <div class="col-md-4">
                <!-- <div class="content-section"> -->
                <ul class="list-group">
                    {% if current_user.is_authenticated %}
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('users.user_posts', username=current_user.username) }}">Your
                            Posts</a></li>


                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('users.user_transactions', username=current_user.username) }}">Your
                            Transactions</a></li>

                    {% endif %}
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('main.weather') }}">Weather</a>
                    </li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
            </div>
            <!-- </div> -->
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

application/templates/create_post.html
{% extends 'base.html' %}
{% block head %}
<title>New Post</title>
{% endblock %}
{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>

            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>{% endblock %}

application/templates/home.html
{% extends 'base.html' %}
{% block head %}
<title>Home</title>
{% endblock %}
{% block body %}
{% for post in posts.items %}
<article class="media content-section">
    <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{
                post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock %}

application/templates/login.html
{% extends 'base.html' %}
{% block head %}
<title>Log In</title>
{% endblock %}
{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log in</legend>

            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <small class="text muted ml-2">
            <a href="#">Forgot Password?</a>
        </small>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up now</a>
    </small>
</div>
{% endblock %}

application/templates/new_transaction.html
{% extends 'base.html' %}
{% block head %}
<title>New Transaction</title>
{% endblock %}

{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>

            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.amount_paid.label(class="form-control-label") }}
                {% if form.amount_paid.errors %}
                {{ form.amount_paid(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.amount_paid.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.amount_paid(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.amount_received.label(class="form-control-label") }}
                {% if form.amount_received.errors %}
                {{ form.amount_received(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.amount_received.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.amount_received(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>{% endblock %}

application/templates/post.html
{% extends 'base.html' %}
{% block head %}
<title>Post No.{{post.id}}</title>
{% endblock %}

{% block body %}
<article class="media content-section">
    <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{
                post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1"
                    href="{{ url_for('posts.update_post', post_id=post.id) }}">Update
                    Post</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                    data-target="#deleteModal">Delete Post</button>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

application/templates/register.html
{% extends 'base.html' %}
{% block head %}
<title>Register</title>
{% endblock %}
{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>
{% endblock %}

application/templates/transaction.html
{% extends 'base.html' %}
% block head %}
<title>Transaction</title>
{% endblock %}
{% block body %}
<article class="media content-section">
    <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_pics/'+transaction.creator.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_transactions', username=transaction.creator.username) }}">{{
                transaction.creator.username }}</a>
            <small class="text-muted">{{ transaction.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <p class="article-content">{{ transaction.content }}</p>
        <p>Amount Paid = {{ transaction.amount_paid }}</p>
        <p>Amount Received = {{ transaction.amount_received }}</p>
        <p>Total = {{ transaction.amount_paid - transaction.amount_received}}</p>
    </div>
</article>
<!-- Modal -->
{% endblock %}

application/templates/troezians.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    {% block head %}
    <title>Troezians</title>
    {% endblock %}
</head>

<body>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Photo</th>
                <th scope="col">Tag</th>
            </tr>
        </thead>

        <tbody>
            {% for tag in tags %}
            <tr>
                <td>{{ tag.name }}</td>
                <td><img class="img-fluid img-thumbnail" style="width:200px;height:auto;"
                        src="{{ url_for('static', filename='troezians/' + tag.name + tag.ext) }}">
                </td>
                <td>{{ tag.tag }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>